CREATE TABLE "User" (
  id SERIAL PRIMARY KEY,
  "telegramId" BIGINT UNIQUE NOT NULL,
  username VARCHAR(255),
  plan VARCHAR(20) DEFAULT 'free',
  status VARCHAR(20) DEFAULT 'active',
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "expiresAt" TIMESTAMP
);

CREATE TABLE "Server" (
  id SERIAL PRIMARY KEY,
  hostname VARCHAR(255) NOT NULL,
  ip VARCHAR(255) UNIQUE NOT NULL,
  location VARCHAR(50),
  "portFree" INTEGER DEFAULT 8443,
  "portPremium" INTEGER DEFAULT 9443,
  status VARCHAR(20) DEFAULT 'active'
);

CREATE TABLE "VpnKey" (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER REFERENCES "User"(id) ON DELETE CASCADE,
  "serverId" INTEGER REFERENCES "Server"(id),
  uuid VARCHAR(255) UNIQUE NOT NULL,
  "shortId" VARCHAR(32) NOT NULL,
  sni VARCHAR(255) NOT NULL,
  port INTEGER NOT NULL,
  status VARCHAR(20) DEFAULT 'active',
  "trafficUsed" BIGINT DEFAULT 0,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "expiresAt" TIMESTAMP
);